 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/commercial_units", type: :request do
  # CommercialUnit. As you add validations to CommercialUnit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CommercialUnit.create! valid_attributes
      get commercial_units_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      commercial_unit = CommercialUnit.create! valid_attributes
      get commercial_unit_url(commercial_unit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_commercial_unit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      commercial_unit = CommercialUnit.create! valid_attributes
      get edit_commercial_unit_url(commercial_unit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CommercialUnit" do
        expect {
          post commercial_units_url, params: { commercial_unit: valid_attributes }
        }.to change(CommercialUnit, :count).by(1)
      end

      it "redirects to the created commercial_unit" do
        post commercial_units_url, params: { commercial_unit: valid_attributes }
        expect(response).to redirect_to(commercial_unit_url(CommercialUnit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CommercialUnit" do
        expect {
          post commercial_units_url, params: { commercial_unit: invalid_attributes }
        }.to change(CommercialUnit, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post commercial_units_url, params: { commercial_unit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested commercial_unit" do
        commercial_unit = CommercialUnit.create! valid_attributes
        patch commercial_unit_url(commercial_unit), params: { commercial_unit: new_attributes }
        commercial_unit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the commercial_unit" do
        commercial_unit = CommercialUnit.create! valid_attributes
        patch commercial_unit_url(commercial_unit), params: { commercial_unit: new_attributes }
        commercial_unit.reload
        expect(response).to redirect_to(commercial_unit_url(commercial_unit))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        commercial_unit = CommercialUnit.create! valid_attributes
        patch commercial_unit_url(commercial_unit), params: { commercial_unit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested commercial_unit" do
      commercial_unit = CommercialUnit.create! valid_attributes
      expect {
        delete commercial_unit_url(commercial_unit)
      }.to change(CommercialUnit, :count).by(-1)
    end

    it "redirects to the commercial_units list" do
      commercial_unit = CommercialUnit.create! valid_attributes
      delete commercial_unit_url(commercial_unit)
      expect(response).to redirect_to(commercial_units_url)
    end
  end
end
