 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/complex_buildings", type: :request do
  # ComplexBuilding. As you add validations to ComplexBuilding, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ComplexBuilding.create! valid_attributes
      get complex_buildings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      complex_building = ComplexBuilding.create! valid_attributes
      get complex_building_url(complex_building)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_complex_building_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      complex_building = ComplexBuilding.create! valid_attributes
      get edit_complex_building_url(complex_building)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ComplexBuilding" do
        expect {
          post complex_buildings_url, params: { complex_building: valid_attributes }
        }.to change(ComplexBuilding, :count).by(1)
      end

      it "redirects to the created complex_building" do
        post complex_buildings_url, params: { complex_building: valid_attributes }
        expect(response).to redirect_to(complex_building_url(ComplexBuilding.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ComplexBuilding" do
        expect {
          post complex_buildings_url, params: { complex_building: invalid_attributes }
        }.to change(ComplexBuilding, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post complex_buildings_url, params: { complex_building: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested complex_building" do
        complex_building = ComplexBuilding.create! valid_attributes
        patch complex_building_url(complex_building), params: { complex_building: new_attributes }
        complex_building.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the complex_building" do
        complex_building = ComplexBuilding.create! valid_attributes
        patch complex_building_url(complex_building), params: { complex_building: new_attributes }
        complex_building.reload
        expect(response).to redirect_to(complex_building_url(complex_building))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        complex_building = ComplexBuilding.create! valid_attributes
        patch complex_building_url(complex_building), params: { complex_building: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested complex_building" do
      complex_building = ComplexBuilding.create! valid_attributes
      expect {
        delete complex_building_url(complex_building)
      }.to change(ComplexBuilding, :count).by(-1)
    end

    it "redirects to the complex_buildings list" do
      complex_building = ComplexBuilding.create! valid_attributes
      delete complex_building_url(complex_building)
      expect(response).to redirect_to(complex_buildings_url)
    end
  end
end
